<?php

namespace Vyper\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MangaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MangaRepository extends EntityRepository
{
    public function myFindAll()
    {
        $queryBuilder = $this->createQueryBuilder('m');
        $queryBuilder->where('m.deleted = false');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }

    public function showAll($magazines_per_page, $page)
    {
        if ($page < 1) {
            throw new \InvalidArgumentException('Can not be < 1');
        }

        $queryBuilder = $this->createQueryBuilder('m');
        $queryBuilder
            ->where('m.deleted = false')
            ->orderBy('m.created', 'DESC')
        ;
        $query = $queryBuilder->getQuery();


        $query
            ->setFirstResult(($page-1) * $magazines_per_page)
            ->setMaxResults($magazines_per_page)
        ;

        return new Paginator($query);
    }
}
