<?php

namespace Vyper\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends EntityRepository
{
    public function myFindAll()
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->where('p.deleted = false');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }

    public function getByAlbum($album)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder
            ->join('p.album', 'album', 'WITH', 'album.id = :id')
            ->where('p.deleted = false')
            ->orderBy('p.created', 'ASC')
            ->setMaxResults(1)
            ->setParameter('id', $album);
        ;
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results[0];
    }

    public function showRandom($concert)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder
            ->join('p.album', 'album', 'WITH', 'album.id = p.album')
            ->where('p.deleted = false')
            ->andWhere('album.category = :concert')
            ->setParameter('concert', $concert);
        ;
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;

    }
}
