<?php

namespace Vyper\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRepository extends EntityRepository
{
    public function songAlreadyRegistered($artist, $title)
    {
        $queryBuilder = $this->createQueryBuilder('v');
        $queryBuilder
            ->select('COUNT(v.id) as nb')
            ->where('v.artist = :artist')
            ->andWhere('v.title = :title')
            ->setParameter('artist', $artist)
            ->setParameter('title', $title)
        ;

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();


        if ($results[0]['nb'] > 0) {
            return $readonly = true;
        } else {
            return $readonly = false;
        }
    }

    public function findByArtistTitle($artist, $title)
    {
        $queryBuilder = $this->createQueryBuilder('v');
        $queryBuilder
            ->where('v.artist = :artist')
            ->andWhere('v.title = :title')
            ->setParameter('artist', $artist)
            ->setParameter('title', $title)
        ;
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
