<?php

namespace Vyper\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitRepository extends EntityRepository
{
    public function findVisit($options) {

        $earlier = new \DateTime('now');
        $earlier = $earlier->sub(new \DateInterval('PT1H'));

        $queryBuilder = $this->createQueryBuilder('v');
        $queryBuilder
            ->where('v.article = :article')
            ->andWhere('v.ip = :ip')
            ->andWhere('v.created > :earlier')
            ->setParameter('article', $options['item'])
            ->setParameter('ip'     , $options['ip'])
            ->setParameter('earlier', $earlier)
        ;

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
