index:
    path:     /
    defaults: { _controller: VyperSiteBundle:Index:index }

home:
    path:     /home
    defaults: { _controller: VyperSiteBundle:Index:index }

login:
    path:     /login
    defaults: { _controller: VyperSiteBundle:Users:login }
