index:
    path:     /
    defaults: { _controller: VyperSiteBundle:Index:index }

home:
    path:     /home
    defaults: { _controller: VyperSiteBundle:Index:index }

login:
    path:     /login
    defaults: { _controller: VyperSiteBundle:Users:login }

admin_show_articles:
    path:     /_admin_/articles
    defaults: { _controller: VyperSiteBundle:AdminArticle:showArticles }

admin_add_article:
    path:     /_admin_/articles/add
    defaults: { _controller: VyperSiteBundle:AdminArticle:addArticles }

admin_add_theme:
    path:     /_admin_/themes/add
    defaults: { _controller: VyperSiteBundle:AdminTheme:addTheme }

admin_update_theme:
    path:     _admin_/theme/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminTheme:updateTheme }
    requirements:
        id: \d+

admin_delete_theme:
    path:     /_admin_/themes/add/{id}
    defaults: { _controller: VyperSiteBundle:AdminTheme:addTheme }
    requirements:
        id: \d+