index:
    path:     /
    defaults: { _controller: VyperSiteBundle:Index:index }

home:
    path:     /home
    defaults: { _controller: VyperSiteBundle:Index:index }

showAllArticle:
    path:    /news/{page}
    defaults: { _controller: VyperSiteBundle:Article:showAll, page: 1 }
    requirements:
        page: \d*

showArticle:
    path:    /articles/{id}/{slug}.html
    defaults: { _controller: VyperSiteBundle:Article:showArticle }
    requirements:
        id: \d+

admin_show_articles:
    path:     /_admin_/articles
    defaults: { _controller: VyperSiteBundle:AdminArticle:showArticles }

admin_add_article:
    path:     /_admin_/article/add
    defaults: { _controller: VyperSiteBundle:AdminArticle:addArticle }

admin_update_article:
    path:     _admin_/article/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminArticle:updateArticle }
    requirements:
        id: \d+

admin_show_events:
    path:     /_admin_/events
    defaults: { _controller: VyperSiteBundle:AdminEvent:showEvents }

admin_add_event:
    path:     /_admin_/event/add
    defaults: { _controller: VyperSiteBundle:AdminEvent:addEvent }

admin_update_event:
    path:     _admin_/event/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminEvent:updateEvent }
    requirements:
        id: \d+

admin_show_locations:
    path:     /_admin_/locations
    defaults: { _controller: VyperSiteBundle:AdminLocation:showLocations }

admin_add_location:
    path:     /_admin_/location/add
    defaults: { _controller: VyperSiteBundle:AdminLocation:addLocation }

admin_update_location:
    path:     _admin_/location/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminLocation:updateLocation }
    requirements:
        id: \d+

admin_add_theme:
    path:     /_admin_/themes/add
    defaults: { _controller: VyperSiteBundle:AdminTheme:addTheme }

admin_update_theme:
    path:     _admin_/theme/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminTheme:updateTheme }
    requirements:
        id: \d+

admin_delete_theme:
    path:     /_admin_/themes/delete/{id}
    defaults: { _controller: VyperSiteBundle:AdminTheme:deleteTheme }
    requirements:
        id: \d+

admin_switchThemeShowInMenu:
   path:    /_admin_/ajax/switch_theme_show_in_menu
   defaults: { _controller: VyperSiteBundle:AdminAjax:toto }

admin_show_pictures:
    path:     /_admin_/pictures
    defaults: { _controller: VyperSiteBundle:AdminPicture:showPictures }

admin_add_picture:
    path:     /_admin_/picture/add
    defaults: { _controller: VyperSiteBundle:AdminPicture:addPicture }

admin_show_tours:
    path:     /_admin_/tours
    defaults: { _controller: VyperSiteBundle:AdminTour:showTours }

admin_add_tour:
    path:     /_admin_/tour/add
    defaults: { _controller: VyperSiteBundle:AdminTour:addTour }

admin_update_tour:
    path:     _admin_/tour/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminTour:updateTour }
    requirements:
        id: \d+

admin_add_tourType:
    path:     /_admin_/tourType/add
    defaults: { _controller: VyperSiteBundle:AdminTourType:addTourType }

admin_update_tourType:
    path:     _admin_/tourType/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminTourType:updateTourType }
    requirements:
        id: \d+

admin_add_album:
    path:     /_admin_/album/add
    defaults: { _controller: VyperSiteBundle:AdminAlbum:addAlbum }

admin_update_album:
    path:     _admin_/album/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminAlbum:updateAlbum }
    requirements:
        id: \d+

admin_show_artists:
    path:     /_admin_/artists
    defaults: { _controller: VyperSiteBundle:AdminArtist:showArtists }

admin_add_artist:
    path:     /_admin_/artist/add
    defaults: { _controller: VyperSiteBundle:AdminArtist:addArtist }

admin_update_artist:
    path:     _admin_/artist/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminArtist:updateArtist }
    requirements:
        id: \d+

ajax_articleArtistLink:
    path:     /_admin_/ajax/article_artist_link
    defaults: { _controller: VyperSiteBundle:AdminAjax:articleArtistLink }

ajax_articleArtistLinkDelete:
    path:     /_admin_/ajax/article_artist_link_delete
    defaults: { _controller: VyperSiteBundle:AdminAjax:articleArtistLinkDelete }

ajax_albumArtistLink:
    path:     /_admin_/ajax/album_artist_link
    defaults: { _controller: VyperSiteBundle:AdminAjax:albumArtistLink }

ajax_albumArtistLinkDelete:
    path:     /_admin_/ajax/album_artist_link_delete
    defaults: { _controller: VyperSiteBundle:AdminAjax:albumArtistLinkDelete }

ajax_eventArtistLink:
    path:     /_admin_/ajax/event_artist_link
    defaults: { _controller: VyperSiteBundle:AdminAjax:eventArtistLink }

ajax_eventArtistLinkDelete:
    path:     /_admin_/ajax/event_artist_link_delete
    defaults: { _controller: VyperSiteBundle:AdminAjax:eventArtistLinkDelete }

