index:
    path:     /
    defaults: { _controller: VyperSiteBundle:Index:index }

home:
    path:     /home
    defaults: { _controller: VyperSiteBundle:Index:index }

showAllArticle:
    path:    /news/{page}
    defaults: { _controller: VyperSiteBundle:Article:showAll, page: 1 }
    requirements:
        page: \d*

showArticle:
    path:    /articles/{id}/{slug}.html
    defaults: { _controller: VyperSiteBundle:Article:showArticle }
    requirements:
        id: \d+

admin_show_articles:
    path:     /_admin_/articles
    defaults: { _controller: VyperSiteBundle:AdminArticle:showArticles }

admin_add_article:
    path:     /_admin_/article/add
    defaults: { _controller: VyperSiteBundle:AdminArticle:addArticle }

admin_update_article:
    path:     _admin_/article/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminArticle:updateArticle }
    requirements:
        id: \d+

admin_add_theme:
    path:     /_admin_/themes/add
    defaults: { _controller: VyperSiteBundle:AdminTheme:addTheme }

admin_update_theme:
    path:     _admin_/theme/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminTheme:updateTheme }
    requirements:
        id: \d+

admin_delete_theme:
    path:     /_admin_/themes/delete/{id}
    defaults: { _controller: VyperSiteBundle:AdminTheme:deleteTheme }
    requirements:
        id: \d+

admin_switchThemeShowInMenu:
   path:    /_admin_/ajax/switch_theme_show_in_menu
   defaults: { _controller: VyperSiteBundle:AdminAjax:toto }

admin_show_pictures:
    path:     /_admin_/pictures
    defaults: { _controller: VyperSiteBundle:AdminPicture:showPictures }

admin_add_picture:
    path:     /_admin_/picture/add
    defaults: { _controller: VyperSiteBundle:AdminPicture:addPicture }

admin_add_album:
    path:     /_admin_/album/add
    defaults: { _controller: VyperSiteBundle:AdminAlbum:addAlbum }

admin_update_album:
    path:     _admin_/album/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminAlbum:updateAlbum }
    requirements:
        id: \d+

admin_show_artists:
    path:     /_admin_/artists
    defaults: { _controller: VyperSiteBundle:AdminArtist:showArtists }

admin_add_artist:
    path:     /_admin_/artist/add
    defaults: { _controller: VyperSiteBundle:AdminArtist:addArtist }

admin_update_artist:
    path:     _admin_/artist/update/{id}
    defaults: { _controller: VyperSiteBundle:AdminArtist:updateArtist }
    requirements:
        id: \d+
