parameters:
#    vyper_site.example.class: Vyper\SiteBundle\Example

services:
#    vyper_site.example:
#        class: %vyper_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
