parameters:
#    vyper_site.example.class: Vyper\SiteBundle\Example

services:
    saysa_view:
        class: Vyper\SiteBundle\Components\View\View
#    vyper_site.example:
#        class: %vyper_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
